#define GSL_SIZEOF_PTH_MUTEX_T		(@GSL_SIZEOF_PTH_MUTEX_T@)
#define GSL_SIZEOF_PTH_COND_T		(@GSL_SIZEOF_PTH_COND_T@)
#define GSL_HAVE_MUTEXATTR_SETTYPE	(@GSL_HAVE_MUTEXATTR_SETTYPE@ && \
					GSL_SIZEOF_PTH_MUTEX_T && \
					GSL_SIZEOF_PTH_COND_T)
#define GSL_SIZEOF_STD_INTMAX_T		(@GSL_SIZEOF_STD_INTMAX_T@)
#define GSL_HAVE_LIBMAD			(@GSL_HAVE_LIBMAD@)
#define GSL_HAVE_OGGVORBIS		(@GSL_HAVE_OGGVORBIS@)
#define GSL_HAVE_OGGVORBIS_RC3		(0)
#define GSL_USE_GSL_GLIB		(1)
#define GSL_USE_ARTS_THREADS		(1)
